model:
  n_models: 10
  seed: 42
  
mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "fraud_detection_continuous"

mlflow_continious:
  experiment_name: "fraud_detection_incremental"